# Generated by Django 5.0.7 on 2024-07-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_productcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='product',
        ),
    ]
